title: jofra
# description: "TODO: Blog description"
author:
  name: "jofra"

baseurl: /

source: .
destination: ./_site
permalink: /:title

# jekyll-paginate (https://jekyllrb.com/docs/pagination/)
# paginator.page                The number of the current page
# paginator.per_page            Number of posts per page
# paginator.posts               Posts available for the current page
# paginator.total_posts         Total number of posts
# paginator.total_pages         Total number of pages
# paginator.previous_page       The number of the previous page, or nil if no previous page exists
# paginator.previous_page_path  The path to the previous page, or nil if no previous page exists
# paginator.next_page           The number of the next page, or nil if no subsequent page exists
# paginator.next_page_path      The path to the next page, or nil if no subsequent page exists

paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

# jekyll-sitemap: generates a sitemap.xml file for crawling purposes
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Custom variables
google_analytics : "UA-102896129-1"
# owner : "SomeHacker"
# year : "2020"
