source: .
destination: ./_site

baseurl: /
title: jofra
# description: "TODO: Blog description"

author:
  name: "jofra"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      authors: ["jofra"]
  -
    scope:
        path: ""
        type: tags
    values:
        layout: "tag"
  -
    scope:
        path: ""
        type: projects
    values:
        layout: "post"
        authors: ["jofra"]
  -
    scope:
        path: ""
        type: articles
    values:
        layout: "post"
        authors: ["jofra"]

collections:
  tags:
    output: true
  articles:
    output: true
  projects:
    output: true

# "_posts" permalink
permalink: /ctf/:title

# jekyll-paginate (https://jekyllrb.com/docs/pagination/)
paginate: 50
paginate_path: /page/:num/

# jekyll-compress-html (https://github.com/penibelst/jekyll-compress-html)
compress_html:
  clippings: all
  endings: []
  comments: ["<!-- ", " -->"]
  ignore:
    envs: []
  blanklines: false
  profile: false

# sass
sass:
    sass_dir: _sass
    style: compact

# Should publish post with dates in the future
future: false

# jekyll-feed: generated feed.xml automatically (for RSS)
# jekyll-sitemap: generates a sitemap.xml file for crawling purposes
# jekyll-seo-tag: generates metadata for better indenting and display of content in link previews
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Custom variables
google_analytics : "UA-102896129-1"
# owner : "SomeHacker"
# year : "2020"
